apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: civpulse-infra
  labels:
    app: postgresql
    managed-by: kubectl
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql
  namespace: civpulse-infra
  labels:
    app: postgresql
    managed-by: kubectl
subsets:
  - addresses:
      - ip: 100.67.17.69
    ports:
      - port: 5432
        protocol: TCP
