apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voter-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CivicPulse/voter-api.git
    targetRevision: main
    path: k8s/apps/voter-api-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: civpulse-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
