apiVersion: v1
kind: Service
metadata:
  name: voter-api
  namespace: civpulse-prod
  labels:
    app: voter-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: voter-api
